version: '3'
services:
  dev1:
    build: docker
    privileged: true
    image: vpp-pathtrace
    container_name: vpp-pathtrace-dev1
    networks:
      - net01
      - net02
      - net05
    command: /sbin/init
    volumes:
      - ./docker/setup.conf:/root/setup.conf
    tty: true

  dev2:
    build: docker
    privileged: true
    image: vpp-pathtrace
    container_name: vpp-pathtrace-dev2
    networks:
      - net03
      - net04
      - net05
    command: /sbin/init
    volumes:
      - ./docker/setup2.conf:/root/setup.conf
    tty: true

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
  net01:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
  net02:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.1.0/24
  net03:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.2.0/24
  net04:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.3.0/24
  net05:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.4.0/24
